
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 61
#define YY_END_OF_BUFFER 62
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[270] =
    {   0,
        0,    0,    0,    0,   62,   61,    3,    1,    2,   61,
       60,   46,    2,   54,   55,   44,   42,   41,   43,    7,
       45,   31,   39,   40,   48,   47,   49,   35,   35,   35,
       35,   35,   35,   35,   35,   35,   35,   35,   35,   35,
       35,   35,   56,   57,   58,   60,   59,    5,    6,    0,
        0,   38,    0,    4,    0,   31,   53,   50,   52,   51,
       35,   35,   35,    0,    0,   35,   35,    0,   35,    0,
       21,   21,   35,   35,    0,   35,   35,    0,   12,   35,
       12,   35,    0,    9,   25,    9,   35,    0,   35,    0,
       35,   10,   35,   10,   35,    0,   35,   35,    0,    0,

        0,    9,    0,    0,    0,   10,   25,    9,    0,   37,
       32,   24,   24,   35,    0,    0,    0,   24,   35,    0,
       35,    0,    0,   35,    0,   35,    0,   35,    0,   28,
       28,   28,   35,    0,   20,   20,   20,   35,    0,   26,
       26,   35,    0,   35,    0,   35,    0,   35,    0,    0,
       15,   15,   35,    0,   35,    0,    0,   15,    0,    0,
       24,   24,   20,    0,    0,    0,   15,   26,   15,   35,
        0,   36,    0,   35,    0,   35,    0,    0,   19,   19,
       35,    0,   14,   14,   35,    0,   35,    0,   35,    0,
       29,   17,   17,   29,   17,   13,   13,   33,   33,   13,

       35,    0,   35,    0,    0,   17,   13,    0,   33,   17,
        0,   14,   17,   13,   13,   23,   23,   27,   27,   35,
        0,   27,   35,    0,   34,   34,   35,    0,   35,    0,
       22,   22,   30,   30,   22,    0,   23,    0,   22,   22,
       22,   35,    0,   11,   11,   35,    0,   35,    0,   35,
        0,   11,    0,    0,    0,   11,   18,   18,   16,   16,
        8,    8,   30,   30,    8,    8,   18,    8,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    1,    5,    6,    6,    7,    6,    8,    9,
       10,   11,   12,   13,   14,   15,   16,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   18,   19,   20,
       21,   22,    1,    6,   23,   24,   25,   26,   27,   28,
       29,   30,   31,   32,   32,   33,   34,   35,   36,   37,
       32,   38,   39,   40,   41,   42,   43,   32,   44,   32,
       45,    1,   46,    6,   47,    6,   23,   24,   25,   26,

       27,   28,   29,   30,   31,   32,   32,   33,   34,   35,
       36,   37,   32,   38,   39,   40,   41,   42,   43,   32,
       44,   32,   48,   49,   50,    6,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[51] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    3,    1,    1,    1,
        1,    1,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    5,    6,    7,    1,    5,    1
    } ;

static const flex_int16_t yy_base[276] =
    {   0,
        0,    0,  548,  541,  481,  640,  640,  640,  640,   47,
      640,  640,    0,  640,  640,  640,  640,  640,  640,  640,
      462,   38,  450,  640,   35,  640,  386,   23,   33,   32,
       18,   31,   47,   26,   56,   49,   59,   41,   61,   73,
       50,   82,  640,  640,  640,  109,  640,  640,  640,  109,
      111,  640,  392,  640,  345,   85,  640,  640,  640,  640,
       44,   81,   79,  313,   97,  104,   89,  112,  106,  117,
      107,   16,  115,  131,  133,  129,  130,  132,  118,  143,
      137,  144,  145,  124,  142,  640,  154,  159,  173,  148,
      171,  155,  160,  180,  168,  174,  179,  188,  183,  192,

      211,  640,  204,  187,  212,  206,  226,  253,  243,  640,
      264,  166,  640,  220,  222,  222,  156,  228,  225,  223,
      250,  217,  254,  252,  260,  265,  224,  277,   94,  262,
      640,  278,  267,  239,  268,  640,  269,  288,  292,  275,
      640,  294,  296,  295,  303,  297,  299,  304,  308,  320,
      305,  640,  318,  323,  319,  321,  325,  327,  347,  344,
      640,  311,  348,  361,  365,  356,  363,  360,  392,  350,
      214,  640,   73,  357,  373,  384,  377,  389,  326,  640,
      394,  388,  368,  640,  408,  393,  407,  411,  406,  409,
      400,  401,  640,  640,  640,  414,  640,  416,  640,  640,

      421,  427,  435,  437,  440,  433,  442,  445,  452,  640,
      450,  444,  448,  434,  471,  458,  640,  459,  640,  469,
      464,  472,  474,  476,  477,  640,  489,  475,  482,  494,
      483,  640,  496,  497,  500,  512,  514,  513,  516,  517,
      531,  507,  520,  508,  640,  530,  521,  537,  538,  539,
      541,  542,  558,  560,  548,  564,  536,  640,  551,  640,
      556,  640,  559,  640,  640,  640,  640,  640,  640,  613,
      620,   70,  625,  630,  632
    } ;

static const flex_int16_t yy_def[276] =
    {   0,
      269,    1,  270,  270,  269,  269,  269,  269,  269,  271,
      269,  269,  272,  269,  269,  269,  269,  269,  269,  269,
      269,  269,  269,  269,  269,  269,  269,  273,  273,  273,
      273,  273,  273,  273,  273,  273,  273,  273,  273,  273,
      273,  273,  269,  269,  269,  269,  269,  269,  269,  271,
      271,  269,  269,  269,  269,  269,  269,  269,  269,  269,
      273,  273,  273,  274,  269,  273,  273,  269,  273,  269,
      273,  269,  273,  273,  269,  273,  273,  269,  273,  273,
      269,  273,  269,  273,  273,  269,  273,  269,  273,  269,
      273,  273,  273,  269,  273,  269,  273,  273,  269,  269,

      269,  269,  269,  269,  269,  269,  269,  269,  271,  269,
      269,  273,  269,  273,  269,  269,  275,  269,  273,  269,
      273,  269,  269,  273,  269,  273,  269,  273,  269,  273,
      269,  269,  273,  269,  273,  269,  269,  273,  269,  273,
      269,  273,  269,  273,  269,  273,  269,  273,  269,  269,
      273,  269,  273,  269,  273,  269,  269,  269,  269,  269,
      269,  269,  269,  269,  269,  269,  269,  269,  269,  273,
      269,  269,  275,  273,  269,  273,  269,  269,  273,  269,
      273,  269,  273,  269,  273,  269,  273,  269,  273,  269,
      273,  273,  269,  269,  269,  273,  269,  273,  269,  269,

      273,  269,  273,  269,  269,  269,  269,  269,  269,  269,
      269,  269,  269,  269,  269,  273,  269,  273,  269,  273,
      269,  269,  273,  269,  273,  269,  273,  269,  273,  269,
      273,  269,  273,  269,  269,  269,  269,  269,  269,  269,
      269,  273,  269,  273,  269,  273,  269,  273,  269,  273,
      269,  269,  269,  269,  269,  269,  273,  269,  273,  269,
      273,  269,  273,  269,  269,  269,  269,  269,    0,  269,
      269,  269,  269,  269,  269
    } ;

static const flex_int16_t yy_nxt[691] =
    {   0,
        6,    7,    8,    9,   10,   11,   12,   13,   14,   15,
       16,   17,   18,   19,   20,   21,   22,   23,   24,   25,
       26,   27,   28,   29,   30,   31,   32,   33,   34,   34,
       35,   34,   34,   34,   36,   37,   38,   39,   34,   40,
       34,   41,   42,   34,   43,   44,    6,   45,   46,   47,
       51,   52,   55,   71,   56,   58,   59,   62,  127,   66,
       63,   69,   64,   73,  127,   74,   72,   64,   67,   76,
       64,   65,   95,   53,  269,   64,   64,   64,   87,   75,
       70,   68,   77,   79,   82,   64,   84,   89,   64,   88,
       80,   64,  269,   64,   64,   78,   85,   83,   96,   55,

       64,   56,   91,   64,   81,   64,  112,   86,   92,   90,
       93,   97,  109,   52,   51,   52,  114,   64,  172,   98,
      184,   94,  113,   64,  121,   64,   64,  115,  124,  113,
       99,  100,  119,   64,  115,  101,  102,  122,  103,  125,
      120,  104,  184,  105,  106,  118,  107,  122,   64,  126,
       64,   64,  120,  128,  125,  127,  130,  108,  131,   64,
      123,  133,   64,  129,  134,  125,  269,  135,   64,  136,
      145,  129,  269,   64,   64,   64,  139,  134,  136,  131,
      137,  132,  138,  140,  141,  139,   64,   64,   64,  142,
      269,  139,  141,  141,  143,  144,  145,  146,   64,   64,

      148,  172,  143,  269,   64,  151,  147,  143,  149,  153,
       64,  152,   64,  157,  269,   64,  152,   64,  155,  147,
      149,  145,  152,   64,  134,  129,  125,  154,  150,  152,
      147,  157,   64,  145,  154,  129,  156,  161,  116,  120,
      158,  122,  170,  136,  171,  141,  109,   52,  127,  177,
      171,  139,  160,  175,  163,  174,  156,  217,  182,  159,
      162,  143,  217,  115,   64,  177,  149,  172,  171,   64,
      171,  175,  182,  175,  164,  165,  171,  186,  161,  147,
      111,  120,  176,  157,  175,  134,  177,  186,  166,  179,
      167,  129,  168,  149,   64,  127,   64,  180,  177,  181,

      180,  169,  178,  183,  184,  185,   64,  186,  180,   64,
      269,   64,   64,  182,  187,  186,  269,  186,  188,   64,
      191,   64,  189,  269,  190,  184,  184,  192,  194,  116,
      198,  196,   64,  197,  199,  195,  188,  188,   64,   64,
      188,   64,  190,  193,  190,  197,  199,  197,   64,   64,
      201,  193,  199,  269,  197,  202,  199,  202,  203,  188,
      204,  111,   64,   64,  204,  186,  202,  204,  200,  204,
       64,  202,  194,  205,  269,  186,  202,  175,  197,  195,
      177,  180,  182,  171,  190,  171,  188,  199,  177,  190,
      194,  218,  207,  216,   64,  206,  208,  195,  217,  110,

      204,   64,  180,  221,  211,  219,   60,  219,  188,  209,
      220,  171,   64,  210,  171,  221,  269,  194,  212,  226,
      190,  219,  175,  219,  213,  221,  214,  224,   64,  180,
      186,  204,  221,  223,  225,  227,  224,  222,   64,  228,
      215,  226,  224,  229,   64,   64,  230,  231,  269,  269,
       64,   64,   64,  232,  230,  228,  226,  230,   64,  228,
       64,  233,  269,  234,  269,   64,  235,  219,  232,  232,
       57,  221,  228,  224,  239,  232,  221,   54,  234,   64,
      269,  219,  224,  234,  224,  234,  243,  230,  235,  230,
      232,  242,  228,  236,  243,  217,  239,  240,  238,  228,

      237,  247,   64,   64,  248,  219,  269,  269,  230,  244,
      224,  245,  243,   64,  217,  246,  249,  243,   64,  241,
      243,   64,  245,  247,  245,  269,   64,   64,  250,  251,
      249,  269,  251,   64,  243,  254,  249,  247,  243,  243,
       64,  257,  249,   49,  251,  251,  251,  245,  251,  251,
       49,   64,   64,  254,  258,  258,  269,  247,  260,  269,
      252,  254,  253,  251,  243,  255,  245,  259,  258,  260,
      261,  262,  269,  263,   64,  264,  258,  269,  260,  256,
       64,   64,  267,   64,  269,  262,  262,  264,  269,  264,
      258,  262,  264,  262,  258,   64,  267,  262,  267,  269,

       64,  260,  269,   64,  269,  269,  265,  269,  266,  269,
      269,  269,  268,   48,   48,   48,   48,   48,   48,   48,
       50,  269,   50,   50,   50,   50,   50,   61,   61,   61,
      269,   61,  117,  117,  173,  173,  269,  173,  173,    5,
      269,  269,  269,  269,  269,  269,  269,  269,  269,  269,
      269,  269,  269,  269,  269,  269,  269,  269,  269,  269,
      269,  269,  269,  269,  269,  269,  269,  269,  269,  269,
      269,  269,  269,  269,  269,  269,  269,  269,  269,  269,
      269,  269,  269,  269,  269,  269,  269,  269,  269,  269
    } ;

static const flex_int16_t yy_chk[691] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
       10,   10,   22,   31,   22,   25,   25,   28,   72,   29,
       28,   30,   31,   32,   72,   32,   31,   28,   29,   33,
       34,   28,   41,  272,   34,   32,   30,   29,   38,   32,
       30,   29,   33,   35,   36,   38,   37,   39,   61,   38,
       35,   33,   61,   36,   41,   33,   37,   36,   41,   56,

       35,   56,   40,   37,   35,   39,   62,   37,   40,   39,
       40,   42,   50,   50,   51,   51,   63,   40,  173,   42,
      129,   40,   65,   63,   67,   62,   42,   63,   69,   62,
       42,   46,   66,   67,   65,   46,   46,   67,   46,   70,
       68,   46,  129,   46,   46,   65,   46,   68,   66,   71,
       69,   71,   66,   73,   69,   71,   74,   46,   75,   73,
       68,   76,   79,   73,   78,   70,   79,   77,   84,   78,
       90,   75,   84,   76,   77,   74,   81,   76,   77,   74,
       78,   75,   80,   82,   83,   81,   85,   80,   82,   87,
       85,   80,   82,   83,   88,   89,   90,   91,   87,   92,

       93,  117,   87,   92,   93,   95,   94,   88,   93,   97,
      112,   96,   95,   99,  112,   91,   95,   89,   98,   91,
       94,   89,   96,   97,  100,  104,  103,   97,   94,  100,
      103,   99,   98,  101,  103,  104,   98,  105,  116,  101,
      100,  106,  114,  106,  115,  106,  109,  109,  106,  122,
      118,  105,  103,  120,  106,  119,  107,  171,  127,  101,
      105,  107,  171,  107,  114,  122,  107,  116,  114,  119,
      115,  120,  127,  119,  107,  108,  118,  134,  108,  108,
      111,  108,  121,  108,  123,  108,  123,  134,  108,  124,
      108,  108,  108,  108,  121,  108,  124,  125,  121,  126,

      124,  108,  123,  128,  132,  133,  130,  137,  125,  126,
      130,  133,  135,  126,  138,  133,  135,  137,  139,  140,
      144,  128,  142,  140,  143,  128,  132,  144,  145,   64,
      148,  146,  138,  147,  149,  145,  138,  162,  142,  144,
      139,  146,  142,  144,  143,  146,  150,  147,  148,  151,
      153,  145,  148,  151,  150,  154,  149,  157,  155,  162,
      156,   55,  153,  155,  157,  158,  153,  155,  150,  156,
      179,  154,  159,  157,  179,  158,  160,  159,  160,  159,
      163,  160,  163,  164,  166,  167,  168,  164,  166,  164,
      165,  174,  160,  170,  170,  159,  163,  165,  170,   53,

      164,  174,  165,  177,  166,  174,   27,  175,  168,  164,
      176,  167,  183,  165,  169,  178,  183,  169,  169,  186,
      169,  175,  169,  178,  169,  177,  169,  182,  176,  169,
      169,  169,  176,  181,  185,  187,  182,  178,  181,  188,
      169,  186,  181,  189,  191,  192,  190,  201,  191,  192,
      189,  187,  185,  202,  189,  187,  185,  190,  196,  188,
      198,  203,  196,  204,  198,  201,  205,  206,  207,  201,
       23,  208,  212,  214,  213,  202,  211,   21,  209,  203,
        5,  206,  214,  203,  208,  204,  221,  211,  205,  209,
      207,  220,  212,  208,  222,  209,  213,  215,  211,  215,

      209,  228,  216,  218,  229,  215,  216,  218,  215,  223,
      215,  224,  221,  220,  215,  227,  230,  220,  223,  215,
      222,  225,  223,  228,  224,  225,  229,  231,  233,  234,
      229,  231,  235,  227,  236,  238,  237,  227,  239,  240,
      233,  242,  230,    4,  233,  234,  237,  236,  235,  240,
        3,  242,  244,  241,  243,  242,  244,  241,  247,    0,
      236,  238,  237,  241,  239,  240,  241,  246,  243,  247,
      248,  249,    0,  250,  246,  251,  252,    0,  246,  241,
      257,  248,  255,  250,  257,  248,  249,  250,    0,  251,
      252,  253,  253,  254,  254,  259,  255,  256,  256,  259,

      261,  256,    0,  263,  261,    0,  253,  263,  254,    0,
        0,    0,  256,  270,  270,  270,  270,  270,  270,  270,
      271,    0,  271,  271,  271,  271,  271,  273,  273,  273,
        0,  273,  274,  274,  275,  275,    0,  275,  275,  269,
      269,  269,  269,  269,  269,  269,  269,  269,  269,  269,
      269,  269,  269,  269,  269,  269,  269,  269,  269,  269,
      269,  269,  269,  269,  269,  269,  269,  269,  269,  269,
      269,  269,  269,  269,  269,  269,  269,  269,  269,  269,
      269,  269,  269,  269,  269,  269,  269,  269,  269,  269
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "VAPS5421.l"
#line 2 "VAPS5421.l"
    #include <stdio.h>
    #include <stdlib.h>
    #include <string.h>
    #include <ctype.h>
    #include "y.tab.h"
    #include "symbol_table.h"
    #include "shared_var.h"
    int i=0;
    int line=1;
#line 689 "lex.yy.c"

#line 691 "lex.yy.c"

#define INITIAL 0
#define SLC 1

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 23 "VAPS5421.l"

#line 911 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 270 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 640 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 24 "VAPS5421.l"
{line++;}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 25 "VAPS5421.l"
{;}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 26 "VAPS5421.l"
{;}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 27 "VAPS5421.l"
{BEGIN(SLC);}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 28 "VAPS5421.l"
{}
	YY_BREAK
case 6:
/* rule 6 can match eol */
YY_RULE_SETUP
#line 29 "VAPS5421.l"
{  line++;BEGIN(INITIAL);}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 30 "VAPS5421.l"
{ table[i].line_number = line;
         strcpy(table[i].lexeme, yytext);
         strcpy(table[i].token, "SEPERATOR");
         i++; return DOT; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 35 "VAPS5421.l"
{ yylval.lexeme = strdup(yytext);table[i].line_number = line;
                                strcpy(table[i].lexeme, yytext);
                                strcpy(table[i].token, "KEYWORD");
                                 
                                i++;return PROGRAM;}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 40 "VAPS5421.l"
{ yylval.lexeme = strdup(yytext);table[i].line_number = line;
                 strcpy(table[i].lexeme, yytext);
                 strcpy(table[i].token, "KEYWORD");
                  
                 i++;return OF;}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 45 "VAPS5421.l"
{yylval.lexeme = strdup(yytext); table[i].line_number = line;
                 strcpy(table[i].lexeme, yytext);
                 strcpy(table[i].token, "KEYWORD");
                  
                 i++;return TO;}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 50 "VAPS5421.l"
{yylval.lexeme = strdup(yytext); table[i].line_number = line;
                 strcpy(table[i].lexeme, yytext);
                 strcpy(table[i].token, "KEYWORD");
                  
                 i++;return DOWNTO;}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 55 "VAPS5421.l"
{ yylval.lexeme = strdup(yytext); table[i].line_number = line;
                 strcpy(table[i].lexeme, yytext);
                 strcpy(table[i].token, "KEYWORD");
                  
                 i++;return IF;}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 60 "VAPS5421.l"
{yylval.lexeme = strdup(yytext); table[i].line_number = line;
                                strcpy(table[i].lexeme, yytext);
                                strcpy(table[i].token, "KEYWORD");
                                 
                                i++;return THEN;}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 65 "VAPS5421.l"
{ yylval.lexeme = strdup(yytext);table[i].line_number = line;
                                strcpy(table[i].lexeme, yytext);
                                strcpy(table[i].token, "KEYWORD");
                                 
                                i++;return ELSE;}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 72 "VAPS5421.l"
{ yylval.lexeme = strdup(yytext);table[i].line_number = line;
                                strcpy(table[i].lexeme, yytext);
                                strcpy(table[i].token, "KEYWORD");
                                 
                                i++;return VAR;}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 77 "VAPS5421.l"
{yylval.lexeme = strdup(yytext); table[i].line_number = line;
                                strcpy(table[i].lexeme, yytext);
                                strcpy(table[i].token, "KEYWORD");
                                 
                                i++;return INT;}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 82 "VAPS5421.l"
{ yylval.lexeme = strdup(yytext);table[i].line_number = line;
                                strcpy(table[i].lexeme, yytext);
                                strcpy(table[i].token, "KEYWORD");
                                 
                                i++;return REAL;}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 87 "VAPS5421.l"
{yylval.lexeme = strdup(yytext); table[i].line_number = line;
                                strcpy(table[i].lexeme, yytext);
                                strcpy(table[i].token, "KEYWORD");
                                 
                                i++;return BOOLEAN;}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 92 "VAPS5421.l"
{yylval.lexeme = strdup(yytext); table[i].line_number = line;
                                strcpy(table[i].lexeme, yytext);
                                strcpy(table[i].token, "KEYWORD");
                                 
                                i++;return CHAR;}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 97 "VAPS5421.l"
{yylval.lexeme = strdup(yytext); table[i].line_number = line;
                                strcpy(table[i].lexeme, yytext);
                                strcpy(table[i].token, "KEYWORD");
                                 
                                i++;return FOR;}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 102 "VAPS5421.l"
{ yylval.lexeme = strdup(yytext);table[i].line_number = line;
                                strcpy(table[i].lexeme, yytext);
                                strcpy(table[i].token, "KEYWORD");
                                 
                                i++;return DO;}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 107 "VAPS5421.l"
{ yylval.lexeme = strdup(yytext);table[i].line_number = line;
                                strcpy(table[i].lexeme, yytext);
                                strcpy(table[i].token, "KEYWORD");
                                 
                                i++;return WHILE;}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 112 "VAPS5421.l"
{yylval.lexeme = strdup(yytext); table[i].line_number = line;
                                strcpy(table[i].lexeme, yytext);
                                strcpy(table[i].token, "KEYWORD");
                                 
                                i++;return ARRAY;}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 117 "VAPS5421.l"
{ yylval.lexeme = strdup(yytext);table[i].line_number = line;
                                strcpy(table[i].lexeme, yytext);
                                strcpy(table[i].token, "KEYWORD");
                                 
                                i++;return AND;}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 122 "VAPS5421.l"
{yylval.lexeme = strdup(yytext); table[i].line_number = line;
                                strcpy(table[i].lexeme, yytext);
                                strcpy(table[i].token, "KEYWORD");
                                 
                                i++;return OR;}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 127 "VAPS5421.l"
{yylval.lexeme = strdup(yytext); table[i].line_number = line;
                                strcpy(table[i].lexeme, yytext);
                                strcpy(table[i].token, "KEYWORD");
                                 
                                i++;return NOT;}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 132 "VAPS5421.l"
{yylval.lexeme = strdup(yytext); table[i].line_number = line;
                                strcpy(table[i].lexeme, yytext);
                                strcpy(table[i].token, "KEYWORD");
                                 
                                i++;return BEG;}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 137 "VAPS5421.l"
{yylval.lexeme = strdup(yytext); table[i].line_number = line;
                                strcpy(table[i].lexeme, yytext);
                                strcpy(table[i].token, "KEYWORD");
                                 
                                i++;return END;}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 142 "VAPS5421.l"
{yylval.lexeme = strdup(yytext); table[i].line_number = line;
                                strcpy(table[i].lexeme, yytext);
                                strcpy(table[i].token, "KEYWORD");
                                 
                                i++;return READ;}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 147 "VAPS5421.l"
{ yylval.lexeme = strdup(yytext);table[i].line_number = line;
                                strcpy(table[i].lexeme, yytext);
                                strcpy(table[i].token, "KEYWORD");
                                 
                                i++;return WRITE;}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 152 "VAPS5421.l"
{yylval.lexeme = strdup(yytext);table[i].line_number = line;
                                strcpy(table[i].lexeme, yytext);
                                strcpy(table[i].token, "INT_LITERAL");
                                 
                                i++;return INT_LITERAL;}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 157 "VAPS5421.l"
{yylval.lexeme = strdup(yytext);table[i].line_number = line;
                                strcpy(table[i].lexeme, yytext);
                                strcpy(table[i].token, "REAL_LITERAL");
                                 
                                i++;return REAL_LITERAL;}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 162 "VAPS5421.l"
{yylval.lexeme = strdup(yytext);table[i].line_number = line;
                                strcpy(table[i].lexeme, yytext);
                                strcpy(table[i].token, "BOOLEAN_LITERAL");
                                 
                                i++;return BOOLEAN_LITERAL;}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 167 "VAPS5421.l"
{yylval.lexeme = strdup(yytext);table[i].line_number = line;
                                strcpy(table[i].lexeme, yytext);
                                strcpy(table[i].token, "BOOLEAN_LITERAL"); 
                                i++;return BOOLEAN_LITERAL;}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 172 "VAPS5421.l"
{yylval.lexeme = strdup(yytext);table[i].line_number = line;
                                strcpy(table[i].lexeme, yytext);
                                 
                                strcpy(table[i].token, "IDENTIFIER");
                                i++;
                                return ID;}  
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 178 "VAPS5421.l"
{yylval.lexeme= strdup(yytext);table[i].line_number = line;
                                strcpy(table[i].lexeme, yytext);
                                 
                                strcpy(table[i].token, "IDENTIFIER");
                                i++;
                                return ARR;}                                 
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 184 "VAPS5421.l"
{yylval.lexeme = strdup(yytext);table[i].line_number = line;
                                strcpy(table[i].lexeme, yytext);
                                strcpy(table[i].token, "CHAR_LITERAL");
                                 
                                i++;return CHAR_LITERAL;}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 189 "VAPS5421.l"
{yylval.lexeme = strdup(yytext);table[i].line_number = line;
                                strcpy(table[i].lexeme, yytext);
                                strcpy(table[i].token, "STRING");
                                 return STRING; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 193 "VAPS5421.l"
{yylval.lexeme = strdup(yytext);table[i].line_number = line;
                                strcpy(table[i].lexeme, yytext);
                                strcpy(table[i].token, "SEPERATOR");
                                 
                                i++;return COLON;}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 198 "VAPS5421.l"
{yylval.lexeme = strdup(yytext);table[i].line_number = line;
                                strcpy(table[i].lexeme, yytext);
                                strcpy(table[i].token, "SEPERATOR");
                                 
                                i++;return SC;}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 203 "VAPS5421.l"
{yylval.lexeme = strdup(yytext);table[i].line_number = line;
                                strcpy(table[i].lexeme, yytext);
                                strcpy(table[i].token, "SEPERATOR");
                                 
                                i++;return COMMA;}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 208 "VAPS5421.l"
{yylval.lexeme = strdup(yytext);table[i].line_number = line;
                                strcpy(table[i].lexeme, yytext);
                                strcpy(table[i].token, "OPERATOR");
                                 
                                i++;return PLUS;}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 213 "VAPS5421.l"
{yylval.lexeme = strdup(yytext);table[i].line_number = line;
                                strcpy(table[i].lexeme, yytext);
                                strcpy(table[i].token, "OPERATOR");
                                 
                                i++;return MINUS;}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 218 "VAPS5421.l"
{yylval.lexeme = strdup(yytext);table[i].line_number = line;
                                strcpy(table[i].lexeme, yytext);
                                strcpy(table[i].token, "OPERATOR");
                                 
                                i++;return MUL;}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 223 "VAPS5421.l"
{yylval.lexeme = strdup(yytext);table[i].line_number = line;
                                strcpy(table[i].lexeme, yytext);
                                strcpy(table[i].token, "OPERATOR");
                                 i++;return DIV;}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 227 "VAPS5421.l"
{yylval.lexeme = strdup(yytext);table[i].line_number = line;
                                strcpy(table[i].lexeme, yytext);
                                strcpy(table[i].token, "OPERATOR");
                                 
                                i++;return MOD;}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 232 "VAPS5421.l"
{yylval.lexeme = strdup(yytext);table[i].line_number = line;
                                strcpy(table[i].lexeme, yytext);
                                strcpy(table[i].token, "OPERATOR");
                                 
                                i++;return EQ;}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 237 "VAPS5421.l"
{yylval.lexeme = strdup(yytext);table[i].line_number = line;
                                strcpy(table[i].lexeme, yytext);
                                strcpy(table[i].token, "OPERATOR");
                                 
                                i++;return LT;}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 242 "VAPS5421.l"
{yylval.lexeme = strdup(yytext);table[i].line_number = line;
                                strcpy(table[i].lexeme, yytext);
                                strcpy(table[i].token, "OPERATOR");
                                 
                                i++;return GT;}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 247 "VAPS5421.l"
{yylval.lexeme = strdup(yytext);table[i].line_number = line;
                                strcpy(table[i].lexeme, yytext);
                                strcpy(table[i].token, "OPERATOR");
                                 
                                i++;return LTEQ;}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 252 "VAPS5421.l"
{yylval.lexeme = strdup(yytext);table[i].line_number = line;
                                strcpy(table[i].lexeme, yytext);
                                strcpy(table[i].token, "OPERATOR");
                                 
                                i++;return GTEQ;}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 257 "VAPS5421.l"
{yylval.lexeme = strdup(yytext);table[i].line_number = line;
                                strcpy(table[i].lexeme, yytext);
                                strcpy(table[i].token, "OPERATOR");
                                 
                                i++;return NOTEQ;}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 262 "VAPS5421.l"
{yylval.lexeme = strdup(yytext);table[i].line_number = line;
                                strcpy(table[i].lexeme, yytext);
                                strcpy(table[i].token, "OPERATOR");
                                 
                                i++;return ASSIGN;}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 267 "VAPS5421.l"
{ yylval.lexeme = strdup(yytext);table[i].line_number = line;
                                strcpy(table[i].lexeme, yytext);
                                strcpy(table[i].token, "SEPERATOR");
                                 
                                i++;return OB;}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 272 "VAPS5421.l"
{ yylval.lexeme = strdup(yytext);table[i].line_number = line;
                                strcpy(table[i].lexeme, yytext);
                                strcpy(table[i].token, "SEPERATOR");
                                 
                                i++;return CB;}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 277 "VAPS5421.l"
{yylval.lexeme = strdup(yytext); table[i].line_number = line;
                                strcpy(table[i].lexeme, yytext);
                                strcpy(table[i].token, "SEPERATOR");
                                 
                                i++;return OPENBRAC;}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 282 "VAPS5421.l"
{yylval.lexeme = strdup(yytext); table[i].line_number = line;
                                strcpy(table[i].lexeme, yytext);
                                strcpy(table[i].token, "SEPERATOR");
                                 
                                i++;return CLOSEBRAC;}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 287 "VAPS5421.l"
{yylval.lexeme = strdup(yytext); table[i].line_number = line;
                                strcpy(table[i].lexeme, yytext);
                                strcpy(table[i].token, "SEPERATOR");
                                 
                                i++;return OPENPARA;}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 292 "VAPS5421.l"
{ yylval.lexeme = strdup(yytext);table[i].line_number = line;
                                strcpy(table[i].lexeme, yytext);
                                strcpy(table[i].token, "SEPERATOR");
                                printf(yytext ); 
                                i++;return CLOSEPARA;}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 297 "VAPS5421.l"
{ ECHO;printf("\n");yyerror(); }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 298 "VAPS5421.l"
ECHO;
	YY_BREAK
#line 1485 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(SLC):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 270 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 270 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 269);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 298 "VAPS5421.l"

void printTable() {
 printf("Symbol Table:\n");
         printf("%-15s %-40s %s\n", "Line Number", "Lexeme", "Token");
         for (int j = 0; j <i; j++) {
                printf("%-15d %-40s %s\n", table[j].line_number, table[j].lexeme, table[j].token);
    }
}
int yywrap()
{
    return 1;
}

